export const ShopActionTypes = {
    CHANGE_VISIBILITY_CART: 'CHANGE_VISIBILITY_CART',
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    DELETE_CART_ITEM: 'DELETE_CART_ITEM',
    DECREASE_COUNT: 'DECREASE_COUNT',
    INCREASE_COUNT: 'INCREASE_COUNT'
};
